// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFKu2tG4cf62qVOcd6Gg2Rsm3LyFRa4s',
    appId: '1:535514083042:web:051ed160dc6ee9f09c78bb',
    messagingSenderId: '535514083042',
    projectId: 'integration-tests-duplicated',
    authDomain: 'integration-tests-duplicated.firebaseapp.com',
    storageBucket: 'integration-tests-duplicated.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmNo4ig5seszjNYmg-Fi8zqtSOBs-dvRU',
    appId: '1:535514083042:ios:0949f5ff8da352239c78bb',
    messagingSenderId: '535514083042',
    projectId: 'integration-tests-duplicated',
    storageBucket: 'integration-tests-duplicated.appspot.com',
    iosClientId: '535514083042-sat805i1emvh38ri7h0a3topi8e78lkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.integrationTestsDuplicated',
  );
}
